version: "3"
services:
    sonarqube:
        image: sonarqube:7.1
        ports:
            - 9000:9000
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:mysql://172.17.0.1:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=sonar
            - MYSQL_DATABASE=sonar
            - MYSQL_PASSWORD=sonar
            - MYSQL_USER=sonar
            - MYSQL_ROOT_HOST=172.17.0.1
    jenkins:
        image: lox1904/jenkins:1.0.0
        ports:
            - 8080:8080
            - 50000:50000
        depends_on:
            - sonarqube
        volumes:
            - jenkins_home:/var/jenkins_home
        links:
            - "sonarqube:sonarqube"
volumes: 
    jenkins_home: